name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - another-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm to version 7
        run: npm install -g npm@7
      - name: Install dependencies
        run: npm install
      - name: Build artifact
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm to version 7
        run: npm install -g npm@7
      - name: Check dependencies for security issues
        run: npm audit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm to version 7
        run: npm install -g npm@7
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test

  lint:
    runs-on
