name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - another-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm to version 7
        run: npm install -g npm@7
      - name: Install dependencies
        run: npm install
      - name: Build artifact
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm to version 7
        run: npm install -g npm@7
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Upgrade npm to version 7
        run: npm install -g npm@7
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build

  post_deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Verify deployment
        run: |
          ssh user@server "curl -f http://localhost/health || exit 1"
